### ISSUE TITLE
FullName Field for users of each realm

### ISSUE THREAD

**Issue by mspark** [Student-Management-System/Sparkyservice-Project#3]
- [x] Add a "fullname" field for local accounts. Editing must be available for local accounts. 
- [x] Query the full name from LDAP. 
If possible, do this directly during login, otherwise, query it separately and safe it to the database.

**Comment by Maze7** [comment]
Also add a "fullname" field for local accounts

**Comment by klingebiel** [comment]
@Maze7 🤔
