### ISSUE TITLE
Swagger-generated client treats PUT /api​/v1​/users as JSON

### ISSUE THREAD

**Issue by adam-sse** [Student-Management-System/Sparkyservice-Project#8]
When creating a new user via PUT /api​/v1​/users the request is expected to contain a simple string with the username. The Swagger-generated Java client treats the request body as JSON, though, so it always adds `"` around the username to serialize it as JSON.

This can probably be fixed by adding a proper Content-Type for this route.

**Comment by mspark** [comment]
@adam-sse pls check and report if this issue is resolved

**Comment by adam-sse** [comment]
Now creation of a new user fails completely, I get the following response:
```json
{"timestamp":"2020.09.03.08.40.46","status":500,"error":"INTERNAL_SERVER_ERROR","messge":"org.springframework.web.bind.MissingServletRequestParameterException","path":""}
```

**Comment by adam-sse** [comment]
I can confirm that this is fixed now.
